title: Risul Islam
description: Fintech domain knowledge & engineering notes
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "fintech"
      type: "pages"
    values:
      layout: fintech
