title: Risul Islam
description: Personal knowledge base
theme: jekyll-theme-cayman
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: "fintech"
      type: "pages"
    values:
      layout: article
      section: fintech